IF(EXISTS "${CMAKE_BINARY_DIR}/PathsCustomInclude.cmake")
 INCLUDE("${CMAKE_BINARY_DIR}/PathsCustomInclude.cmake")
ENDIF()

#Doxygen related

IF(NOT DEFINED DOXYGEN_EXECUTABLE)
 IF(DEFINED PCI_DOXYGEN_EXECUTABLE)
  SET(DOXYGEN_EXECUTABLE "${PCI_DOXYGEN_EXECUTABLE}" CACHE FILEPATH "Doxygen executable")
 ELSE()
  SET(DOXYGEN_EXECUTABLE "XXXSETME-NOTFOUND" CACHE FILEPATH "Doxygen executable")
  MESSAGE(FATAL_ERROR "PLEASE SET OR DEFAULT DOXYGEN_EXECUTABLE")
 ENDIF()
ENDIF()
