IF(EXISTS "${CMAKE_BINARY_DIR}/PathsCustomInclude.cmake")
 INCLUDE("${CMAKE_BINARY_DIR}/PathsCustomInclude.cmake")
ENDIF()

#PkgConfig related

IF(NOT DEFINED PKG_CONFIG_EXECUTABLE)
 IF(DEFINED PCI_PKG_CONFIG_EXECUTABLE)
  SET(PKG_CONFIG_EXECUTABLE "${PCI_PKG_CONFIG_EXECUTABLE}" CACHE PATH "Pkg-config executable")
 ELSE()
  SET(PKG_CONFIG_EXECUTABLE "XXXSETME-NOTFOUND" CACHE PATH "Pkg-config executable")
  MESSAGE(FATAL_ERROR "PLEASE SET OR DEFAULT PKG_CONFIG_EXECUTABLE")
 ENDIF()
ENDIF()

IF(NOT DEFINED PKG_CONFIG_PATH)
 IF(DEFINED PCI_PKG_CONFIG_PATH)
  SET(PKG_CONFIG_PATH "${PCI_PKG_CONFIG_PATH}" CACHE PATH "Pkg-config path")
 ELSE()
  SET(PKG_CONFIG_PATH "XXXSETME-NOTFOUND" CACHE PATH "Pkg-config path")
  MESSAGE(FATAL_ERROR "PLEASE SET OR DEFAULT PKG_CONFIG_PATH")
 ENDIF()
 #GTK2 (NonFedora) = "C:/testM/Glade/OBS/OBS24/mingw/lib/pkgconfig"
 #GTK3 = "C:/testM/Glade/OBS/mingw/lib/pkgconfig"
ENDIF()

SET(ENV{PKG_CONFIG_PATH} "${PKG_CONFIG_PATH}" CACHE PATH "Magic")

FIND_PACKAGE(PkgConfig)
